start_date: '1980-01-01'
end_date: '1980-12-31'
dt:
  1 # dt is currently hardcoded in the package as 1 day
  # changing this variable won't change anything until
  # we update the underlying package
# no "initial_conditions" key => initialize from constant values
forcing:
  use_cyclic_forcing: False
  streams:
    - forcing_streams/highres/T_pelagic.TL319_t13.4p2z.yaml
    - forcing_streams/highres/T_bottom.TL319_t13.4p2z.yaml
    - forcing_streams/highres/poc_flux_bottom.TL319_t13.4p2z.yaml
    - forcing_streams/highres/zoo_mort.TL319_t13.4p2z.yaml
    - forcing_streams/highres/zooC.TL319_t13.4p2z.yaml
max_output_time_dim: 365
method: euler
num_workers: 48
chunks:
  nlat: 100 # divides into 2400
  nlon: 100 # divides into 3600
output_file: highres.1980.zarr
output_in_2D: true
# Option to pull out a single lat,lon from POP grid
# (could we provide degrees instead of indices?)
# lat_lon: # lat: 0 - 383 on the 1 degree grid; lon: 0 - 319 on the 1 degree grid
#   - 0, 10
#   - 55, 20
